name: Release
on:
  push:
    tags:
      - '*'

jobs:
  # Job: Create release
  release:
    runs-on: ubuntu-latest
    outputs:
      release-notes-url: ${{ steps.create-release.outputs.url }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      # Create release
      - name: Create release
        id: create-release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true

